### ISSUE TITLE
tutorial_gender_classification.ipynb cell 13 crashing: axes don't match array

### ISSUE THREAD

**Issue by romeokienzler** [IBM/ML-Pipelines-101#11]
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-13-96c22229d7ad> in <module>
>       1 batch_size = 64
>       2 
> ----> 3 X_train = X_train.transpose(0,3,1,2)
>       4 X_test = X_test.transpose(0,3,1,2)
>       5 
> 
> ValueError: axes don't match array
>

**Comment by Tomcli** [comment]
at code cell 6
`age, gender, race = image_path.split('\\')[-1].split("_")[:3]`

I think `.split('\\')` only works for window file system. my original code has `.split('/')` which works for linux and mac. Probably we need to add some condition check or use os.path.basename to make sure this won't happen again.

**Comment by romeokienzler** [comment]
Sorry, I just noticed that the image folder was empty, therefore dimensions of training data zero ... closing for now...
