### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/tmp/.art'

### ISSUE THREAD

**Issue by romeokienzler** [IBM/ML-Pipelines-101#12]
In adversarial-training-mnist.ipynb 2nd code cell (Watson Studio):

> ---------------------------------------------------------------------------
> PermissionError                           Traceback (most recent call last)
> <ipython-input-4-ef99c15c18e0> in <module>
> ----> 1 (x_train, y_train), (x_test, y_test), min_, max_ = load_dataset('mnist')
> 
> /opt/conda/envs/Python36/lib/python3.6/site-packages/art/utils.py in load_dataset(name)
>     489 
>     490     if "mnist" in name:
> --> 491         return load_mnist()
>     492     elif "cifar10" in name:
>     493         return load_cifar10()
> 
> /opt/conda/envs/Python36/lib/python3.6/site-packages/art/utils.py in load_mnist(raw)
>     414     from art import DATA_PATH
>     415 
> --> 416     path = get_file('mnist.npz', path=DATA_PATH, url='https://s3.amazonaws.com/img-datasets/mnist.npz')
>     417 
>     418     f = np.load(path)
> 
> /opt/conda/envs/Python36/lib/python3.6/site-packages/art/utils.py in get_file(filename, url, path, extract)
>     554         path_ = os.path.join('/tmp', '.art')
>     555     if not os.path.exists(path_):
> --> 556         os.makedirs(path_)
>     557 
>     558     if extract:
> 
> /opt/conda/envs/Python36/lib/python3.6/os.py in makedirs(name, mode, exist_ok)
>     218             return
>     219     try:
> --> 220         mkdir(name, mode)
>     221     except OSError:
>     222         # Cannot rely on checking for EEXIST, since the operating system
> 
> PermissionError: [Errno 13] Permission denied: '/tmp/.art'

IMHO art.utils.load_dataset needs to be overloaded so that it supports a parameter for the tmp directory since it is RO in WS

**Comment by Tomcli** [comment]
Fixed
