### ISSUE TITLE
Test all Notebooks in Watson Studio

### ISSUE THREAD

**Issue by romeokienzler** [IBM/ML-Pipelines-101#13]
Notebooks working in WS python 3.6:  

Prio 1:
- [x] adversarial-training-mnist.ipynb
- [x] ml-pipeline.ipynb
- [x] tutorial_gender_classification.ipynb (at least 2vCPU/4 GB of RAM runtime required)

Prio 2:
- [ ] mnist_poisoning_demo.ipynb 
- [ ] tutorial_credit_scoring.ipynb
- [ ] tutorial_medical_expenditure.ipynb

**Comment by Tomcli** [comment]
`ml-pipeline.ipynb` and `tutorial_gender_classification.ipynb` work on Watson Studio free python 3.6 (1 cpu 4 GB memory).

**Comment by sveta-levitan** [comment]
adversarial-training-mnist.ipynb is updated for ART 0.9 and works on local machine. It kills the kernel on Watson Studio even before getting into major code, both for me and Tommy. I will try other ART notebooks.

**Comment by sveta-levitan** [comment]
mnist_poisoning_demo.ipynb works well both locally and on Watson Studio, but includes some training that takes time, now about 9 minutes

**Comment by sveta-levitan** [comment]
adversarial-training-mnist-WS.ipynb works well on Watson Studio

**Comment by romeokienzler** [comment]
closing as all necessary notebooks for oscon work
